plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
      message: "chore(release): version ${nextRelease.version}\n\n${nextRelease.notes}"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - publishCmd: |
        rm -rf data src
        sed -i "s/@socialgouv\/fiches-travail-data/@socialgouv\/fiches-travail-data-types/g" package.json
        { rm package.json; jq 'del(.dependencies)' > package.json; } < package.json
        npm version patch
        npm publish
